### ISSUE TITLE
Mounting system

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/BeachRover#12]
Determine if the Camera will be fixed, or on some sort of moving assembly.. i.e., pan/tilt or arm setup?.. again depends on #11 and all of its dependencies, as well as how many RPI pins are available ...

**Comment by ebgoldstein** [comment]
additionally, since we are potentially using a Donkey car as the base, then 3d printing a mount can be done by modifying the DK 3d print files..

**Comment by MichaMung** [comment]
The best way to attach the camera is using a pan-tilt system, as this method allows the camera to be positioned best for each image. A fixed system would require the RC Rover to move around and position the entire rover for images, which would be an added drain on the battery, where a pan-tilt can mitigate this energy waste. The pan-tilt can provide multiple angles and images in the same position and has been very simple to use. The use of LEDs to provide lighting for the camera is best, however that is to be determined depending on the size of the camera relative to the pan-tilt.
