### ISSUE TITLE
Get Ardupilot working on Navio+DonkeyCar

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/BeachRover#8]
depends on #2 and #3..

**Comment by StevenTagner** [comment]
As of 5/15/21:
ArduPilot is working on the Navio, and I can remotely access the computer to see GPS data (in the form of latitude, longitude, and altitude), weather data (in the form of temperature and pressure), and other misc data (Accelerometer, Gyroscope, and Magnetometer for example). I have yet to merge it with Donkey Car to drive it around or save the data in a file and download it to the GCS, these are what I will be working on next.
